USE=core tools colvar

STANMATH=math
ADDCPPFLAGS += -I$(STANMATH) -I$(STANMATH)/lib/eigen_3.3.3/ \
	-I$(STANMATH)/lib/cvodes_2.9.0/include  \
	-I$(STANMATH)/lib/boost_1.62.0/

# generic makefile
include ../maketools/make.module
